spring:
  application:
    name: user-service
  flyway:
    enabled: true
  datasource:
    name: "shahid"
    password: "shahid"
    url: "jdbc:mysql://localhost:3306/home_energy_tracker"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
server:
  port: 4000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true