spring:
  datasource:
    url: jdbc:mysql://localhost:3306/home_energy_tracker
    username: Uzma
    password: shahid
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

#  flyway:
#    enabled: true
server:
  port: 4001